# the services part
services:
#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10
#nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
#redis
  redis:
    image: redis:user
    build: ./requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

#ftp:
  ftp:
    image: ftp:user
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

#adminer
  adminer:
    image: adminer:user
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: always

#portfolio
  website:
    image: website:user
    container_name: website
    build: ./requirements/bonus/website
    ports:
      - "80:80"
    networks:
      - inception
    restart: always

#portainer
  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer/
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/eismail/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/eismail/data/wordpress
      o : bind
      type : none
  portainer:
    name: portainer
    driver: local
    driver_opts:
      device: /home/eismail/data/portainer
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception